version: "3"
services:
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: parkingticket
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
       - 3306:3306

  redis:
    image: redis
    ports:
      - 6379:6379

  parkingticket:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mysql
      - redis
