spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:h2:tcp://localhost/~/parkingticket
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
#        format_sql: true
#        use_sql_comments: true
        default_batch_fetch_size: 100
    open-in-view: false
  redis:
    host: 192.168.99.100
    port: 6379
  url:
    base: http://localhost:8080 # test



logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace
