spring:
  profiles:
    active: local
    include:
      - credential

cloud:
  aws:
    s3:
      bucket: parkingticket-s3
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instanceProfile: true