spring:
  profiles:
    active: local
    include:
      - credential
  social:
    kakao:
      redirect: /social/login/kakao
      url:
        login: https://kauth.kakao.com/oauth/authorize
        token: https://kauth.kakao.com/oauth/token
        profile: https://kapi.kakao.com/v2/user/me


cloud:
  aws:
    s3:
      bucket: parkingticket-s3
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instanceProfile: true

